### ISSUE TITLE
[NF] Add method to get completion status of test run to public api

### ISSUE THREAD

**Issue by DmitryBogatko** [aquality-automation/aquality-tracking#87]
the method is necessary for tasks like running tests AWS lambda in the pipeline - so we have to wait until all tests will be completed. one of the options is to check that the test run does not have 'not executed' tests.

**Comment by VladislavKostyukevich** [comment]
@DmitryBogatko dont think this is a really good idea to rely on number of Not Executed tests because some of them can be not a part of test run for some reason. From my point of view the pipline or aws lambda or framework itself should care about notifying about test execution comletion. Anyway this is a very edge case which is not really related to this Project.
